INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('263037 2913754 22696148', 'Coolmod', 'coolmod.com colmod coolmodcom', 'p a g', 'TRADEDOUBLER');

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('267625 2913754 22938076', 'Fotoalbum', 'fotoalbum.es', 'p a g', 'TRADEDOUBLER');

UPDATE `thatcompany`
SET `TC_AFFILIATE_ID` = '265457 2913754 22855014', `TC_AFFILIATE_ID_KEY` = 'p a g', `TC_WATERMARKS` = 'Gearbest.com Gearbest.es', `TC_COMPANY_AFFILIATE_TYPE` = 'TRADEDOUBLER'
WHERE `TC_NAME` = 'Gearbest';

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('21645 2913754 12469739', 'Lastminute', 'lastminute.es es.lastminute.com', 'p a g', 'TRADEDOUBLER');

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('229716 2913754 20909968', 'La Tostadora', 'latostadora latostadora.com', 'p a g', 'TRADEDOUBLER');

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('48184 2913754 16382842', 'Rumbo', 'rumbo.es', 'p a g', 'TRADEDOUBLER');

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('62399 2913754 17166854', 'Swarovski', 'swarovski.es svaroski swaroski', 'p a g', 'TRADEDOUBLER');

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('260156 2913754 22474266', 'Viajes El Corte Inglés', 'VECI', 'p a g', 'TRADEDOUBLER');
