INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('265462 2913754 22842826', 'Everbuying', 'everbuying.net', 'p a g', 'TRADEDOUBLER');

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('17460 2913754 21283566', 'Casa del Libro', 'casadellibro casadellibro.com', 'p a g', 'TRADEDOUBLER');
