UPDATE `thatcompany`
SET `TC_AFFILIATE_ID` = '24065 989841 265784', `TC_AFFILIATE_ID_KEY` = 'c m a', `TC_WATERMARKS` = 'emp-online.es emp-online', `TC_COMPANY_AFFILIATE_TYPE` = 'TRADETRACKER'
WHERE `TC_NAME` = 'EMP';

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('14916 532131 265784', 'Toy Planet', 'toyplanet toyplanet.es', 'c m a', 'TRADETRACKER');
