UPDATE `thatcompany`
SET `TC_AFFILIATE_ID` = '40816163C860237279T', `TC_AFFILIATE_ID_KEY` = '', `TC_COMPANY_AFFILIATE_TYPE` = 'ZANOX'
WHERE `TC_NAME` = 'Guess';

UPDATE `thatcompany`
SET `TC_AFFILIATE_ID` = '41050400C1620134037T', `TC_AFFILIATE_ID_KEY` = '', `TC_COMPANY_AFFILIATE_TYPE` = 'ZANOX', `TC_NAME` = 'eDreams'
WHERE `TC_NAME` = 'Edreams';

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('41050394C413664037T', 'La Redoute', 'laredoute laredoute.es redoute', '', 'ZANOX');

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('41050496C1483695028T', 'Cash Converters', 'cashconverters cashconverters.es', '', 'ZANOX');

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('41050498C652963078T', 'Ticketmaster', 'ticketmaster ticketmaster.es', '', 'ZANOX');

INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('A5B83584B42A666E5309', 'Imaginarium', 'imaginarium imaginarium.es', '', 'ZANOX');


