INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('265455 2913754 22817710', 'Wuaki TV', 'wuaki.tv es.wuaki.tv', 'p a g', 'TRADEDOUBLER');
