INSERT INTO `thatcompany` (`TC_AFFILIATE_ID`, `TC_NAME`, `TC_WATERMARKS`, `TC_AFFILIATE_ID_KEY`, `TC_COMPANY_AFFILIATE_TYPE`)
VALUES ('A5B83584B42A666E5309', 'Zavvi', 'zavi zavvi.es', '', 'ZANOX');


